name = "Hacker"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/hksanduo/hugo-theme-hacker/master/LICENSE.md"
description = "Hacker theme."
source_repo = "https://github.com/hksanduo/hugo-theme-hacker.git"
tags = ["Responsive", "Blog", "Google analytics", "Disqus", "Clean", "Tags", "Minimal", "Custom Themes", "Minimalist", "Simple", "Pink", "Green", "Starter", "Dark", "Sortable Tables"]
features = ["blog", "sortable tables", "image zoom", "optional pagination"]
min_version = 0.27
[author]
    name = "hksanduo"
    homepage = "https://github.com/hksanduo/hugo-theme-hacker"

